-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgk2LARl3QdxHYVnDq
Nlv7LQJqqk40NRnPKUKDZY3H2hOgCgYIKoZIzj0DAQehRANCAATQ5z0PC8fVIRb2
R1XGvBOP6NX/z4gu5O11pInKqmVIC6fIontnmJ2KyasaJipTADTW6etcJnaHUDKM
MKfjRGOd
-----END PRIVATE KEY-----